### ISSUE TITLE
Work on Input fields and UI improvements

### ISSUE THREAD

**Issue by Abdulwhbhussain** [Salimer/Awesome-books#2]
- After Clicking the Add Button, A Book is Added; Make Sure Input Fields are Empty;
- make Your UI Easier to read and Analyze for a Better UX; Keep it short and in the middle.
- There Should be Space/Seperator between added Books.

**Comment by Salimer** [comment]
Thank you @Abdulwhbhussain for the issue. After adding a book, I added the space between the books and the functionality of the empty input. About the UX we will improve it going on the week as I was implementing the [Low Fidelity Wireframe](https://mentormate.com/blog/low-fidelity-wireframes-vs-high-fidelity-wireframes/) implementation 💯
